name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn clean
      - run: yarn compile
      - run: yarn build
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn cy:compile
      - run: yarn cy:junit
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

      - run: yarn docs
      - run: |
          mkdir -p public/main
          cp -rt public/main/ docs demo/* build/* src/*
          mkdir -p public/app
          cp -rt public/app/ build/LineUpJS.* build/*.ttf build/*.eot build/*.svg

          mkdir -p public_dev/develop
          cp -rt public_dev/develop/ demo/* build/*
          mkdir -p public_dev/app_develop
          cp -rt public_dev/app_develop/ build/LineUpJS.* build/*.ttf build/*.eot build/*.svg

      - name: Deploy build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f build  # Adjust this to your build directory
          git commit -m "Deploy build output"
          git push -f origin `echo $GITHUB_REF | sed -e 's/refs\\/heads\\///'`:`echo $GITHUB_REF | sed -e 's/refs\\/heads\\///'`-build
      
